#!/bin/bash

##### DESCRIPTION ###########################################################
# Wrapper for check_time_mkorzen. To be used with Check_MK agent as local
# type of check.
#
##### USAGE #################################################################
# Place this script in /usr/lib/check_mk_agent/local on server monitored by
# Check_MK.
# Don't forget to adjust path to check_time_mkorzen.py.
#
##### LICENSE ###############################################################
# Copyright 2017 Maciej Korzen
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 dated June, 1991.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
##### AUTHOR ################################################################
# Maciej Korzen
# maciek@korzen.org, mkorzen@gmail.com
# http://www.korzen.org/

timeout 20 /fix_me/path/to/check_mk_agent_local/check_time_mkorzen.py -n time_mkorzen
